// Generates src/data/thirdPlaceAllocation.ts from the official FIFA Annex C table
// (the 495 round-of-32 third-place combinations) published on Wikipedia.
//
// Source: Template:2026 FIFA World Cup third-place table (raw wikitext).
// Winner-column order in the table is fixed: A, B, D, E, G, I, K, L.
// Each data row lists:
//   - the 8 third-place GROUPS that qualify (bold letters in the 12 presence cells)
//   - 8 assignment cells "3X", one per winner column, naming the third-place group
//     that plays that group's winner.
//
// Output: a map from the sorted 8-letter qualifying-group key (e.g. "EFGHIJKL")
// to an 8-char string of third-place groups in winner order [A,B,D,E,G,I,K,L].
//
// Run: node scripts/buildThirdPlaceTable.mjs

import { writeFileSync } from 'node:fs';

const TEMPLATE_URL =
  'https://en.wikipedia.org/w/index.php?title=Template:2026_FIFA_World_Cup_third-place_table&action=raw';

const WINNER_ORDER = ['A', 'B', 'D', 'E', 'G', 'I', 'K', 'L'];

async function main() {
  const res = await fetch(TEMPLATE_URL);
  if (!res.ok) throw new Error(`Fetch failed: ${res.status}`);
  const wikitext = await res.text();

  // Split into table rows on the "|-" row separator.
  const rows = wikitext.split(/\n\|-/);
  const table = {};
  let parsed = 0;

  for (const row of rows) {
    // A data row begins with: ! scope="row" | <number>
    const numMatch = row.match(/!\s*scope="row"\s*\|\s*(\d+)/);
    if (!numMatch) continue;

    // Qualifying groups = the bold letters '''X''' in the presence section.
    const groups = [...row.matchAll(/'''([A-L])'''/g)].map((m) => m[1]);
    if (groups.length !== 8) continue;

    // Assignment cells: every "3X" token, in document order, which matches the
    // winner column order [A,B,D,E,G,I,K,L].
    const assign = [...row.matchAll(/3([A-L])\b/g)].map((m) => m[1]);
    if (assign.length !== 8) continue;

    const key = [...groups].sort().join('');
    const value = assign.join('');

    if (table[key] && table[key] !== value) {
      throw new Error(`Conflicting assignment for ${key}: ${table[key]} vs ${value}`);
    }
    table[key] = value;
    parsed++;
  }

  const uniqueKeys = Object.keys(table).length;
  if (uniqueKeys !== 495) {
    console.warn(`WARNING: expected 495 unique combinations, got ${uniqueKeys} (parsed ${parsed} rows).`);
  }

  // Sanity checks against known rows.
  const checks = [
    ['EFGHIJKL', 'EJIFHGLK'], // option 1
    ['ABCDEFGH', 'HGBCAFDE'], // option 495
  ];
  for (const [k, v] of checks) {
    if (table[k] !== v) {
      throw new Error(`Sanity check failed for ${k}: expected ${v}, got ${table[k]}`);
    }
  }

  const sortedEntries = Object.entries(table).sort(([a], [b]) => a.localeCompare(b));
  const body = sortedEntries.map(([k, v]) => `  ${k}: '${v}',`).join('\n');

  const out = `// AUTO-GENERATED by scripts/buildThirdPlaceTable.mjs — do not edit by hand.
//
// Official FIFA 2026 round-of-32 third-place allocation (Annex C, 495 combinations).
// Key:   sorted 8-letter string of the qualifying third-place groups (e.g. "EFGHIJKL").
// Value: 8-char string of third-place groups in WINNER column order [${WINNER_ORDER.join(', ')}].
//        i.e. value[i] is the third-place group that plays the winner of group WINNER_ORDER[i].

export const THIRD_PLACE_WINNER_ORDER = [${WINNER_ORDER.map((g) => `'${g}'`).join(', ')}] as const;

export const THIRD_PLACE_ALLOCATION: Record<string, string> = {
${body}
};
`;

  const dest = new URL('../src/data/thirdPlaceAllocation.ts', import.meta.url);
  writeFileSync(dest, out);
  console.log(`Wrote ${uniqueKeys} combinations to src/data/thirdPlaceAllocation.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
